<a href="https://colab.research.google.com/github/hansuho113/Machine_learning/blob/main/%EA%B8%B0%EA%B3%84%ED%95%99%EC%8A%B5_12%EC%A3%BC%EC%B0%A8_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

a = tf.random.uniform([2, 3], 0, 1) # [0, 1] 사이의 2*3 행렬 생성
print(a, type(a))

tf.Tensor(
[[0.6370065  0.07501495 0.17547691]
 [0.8525187  0.86503625 0.9818268 ]], shape=(2, 3), dtype=float32) <class 'tensorflow.python.framework.ops.EagerTensor'>


In [ ]:
import numpy as np

t = tf.random.uniform([2, 3], 0, 1)
n = np.random.uniform(0, 1, [2,3])


In [ ]:
print(t)
print(n)

print(t+n)

tf.Tensor(
[[0.6574092  0.61094666 0.8248675 ]
 [0.7676804  0.95748866 0.47046804]], shape=(2, 3), dtype=float32)
[[0.59244814 0.22532169 0.21421251]
 [0.93520794 0.38312047 0.10610454]]
tf.Tensor(
[[1.2498573  0.83626837 1.03908   ]
 [1.7028884  1.3406091  0.5765726 ]], shape=(2, 3), dtype=float32)


In [ ]:
import tensorflow.keras.datasets as ds

(x_train, y_train), (x_test, y_test) = ds.mnist.load_data()
yy_train = tf.one_hot(y_train, 10, dtype=tf.int8)
print("mnist:", x_train.shape, y_train.shape, yy_train.shape)


(x_train, y_train), (x_test, y_test) = ds.cifar10.load_data()
yy_train = tf.one_hot(y_train, 10, dtype=tf.int8)


mnist: (60000, 28, 28) (60000,) (60000, 10)


In [ ]:
x = [[0.0,0.0],[0.0,1.0],[1.0,0.0],[1.0,1.0]]
y = [[-1],[1],[1],[1]]

w = tf.Variable([[1.0], [1.0]])
b = tf.Variable(-0.5)

s = tf.add(tf.matmul(x, w), b)
o = tf.sign(s)

print(o)

tf.Tensor(
[[-1.]
 [ 1.]
 [ 1.]
 [ 1.]], shape=(4, 1), dtype=float32)


In [ ]:
w = tf.Variable(tf.random.uniform([2, 1], -0.5, 0.5))
b = tf.Variable(tf.zeros([1]))

opt = tf.keras.optimizers.SGD(learning_rate=0.1)

def forward():
    s = tf.add(tf.matmul(x, w), b)
    o = tf.tanh(s)
    return o

def loss():
    o = forward()
    return tf.reduce_mean((y-o)**2)

for i in range(500):
    opt.minimize(loss, var_list = [w, b])
    if(i%100 == 0):
        print(f"loss at epoch {i} = {loss().numpy()}")

o = forward()
print(o)

loss at epoch 0 = 0.7895994186401367
loss at epoch 100 = 0.09255778789520264
loss at epoch 200 = 0.04252049699425697
loss at epoch 300 = 0.026684263721108437
loss at epoch 400 = 0.019200799986720085
tf.Tensor(
[[-0.81602913]
 [ 0.8861962 ]
 [ 0.8861869 ]
 [ 0.9992627 ]], shape=(4, 1), dtype=float32)


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD

n_input = 2
n_output=1
perceptron = Sequential()
perceptron.add(Dense(units=n_output,
                     activation='tanh',
                     input_shape=(n_input,),
                     kernel_initializer = 'randon_uniform',
                     bias_initializer='zeros'))

perceptron.compile(loss='mse',
                   optimizer=SGD(learning_rate=0.1),
                   metrics=['mse'])

perceptron.fit(x, y, epochs=500, verbose=2)
res = perceptron.predict(x)

Epoch 1/500
1/1 - 0s - loss: 1.0163 - mse: 1.0163
Epoch 2/500
1/1 - 0s - loss: 0.7590 - mse: 0.7590
Epoch 3/500
1/1 - 0s - loss: 0.6458 - mse: 0.6458
Epoch 4/500
1/1 - 0s - loss: 0.5907 - mse: 0.5907
Epoch 5/500
1/1 - 0s - loss: 0.5577 - mse: 0.5577
Epoch 6/500
1/1 - 0s - loss: 0.5341 - mse: 0.5341
Epoch 7/500
1/1 - 0s - loss: 0.5152 - mse: 0.5152
Epoch 8/500
1/1 - 0s - loss: 0.4988 - mse: 0.4988
Epoch 9/500
1/1 - 0s - loss: 0.4840 - mse: 0.4840
Epoch 10/500
1/1 - 0s - loss: 0.4701 - mse: 0.4701
Epoch 11/500
1/1 - 0s - loss: 0.4570 - mse: 0.4570
Epoch 12/500
1/1 - 0s - loss: 0.4444 - mse: 0.4444
Epoch 13/500
1/1 - 0s - loss: 0.4323 - mse: 0.4323
Epoch 14/500
1/1 - 0s - loss: 0.4207 - mse: 0.4207
Epoch 15/500
1/1 - 0s - loss: 0.4095 - mse: 0.4095
Epoch 16/500
1/1 - 0s - loss: 0.3986 - mse: 0.3986
Epoch 17/500
1/1 - 0s - loss: 0.3882 - mse: 0.3882
Epoch 18/500
1/1 - 0s - loss: 0.3781 - mse: 0.3781
Epoch 19/500
1/1 - 0s - loss: 0.3683 - mse: 0.3683
Epoch 20/500
1/1 - 0s - loss: 0.3589 - m

In [ ]:
import numpy as np
from tensorflow.keras.datasets import mnist
from tensorflow.keras.optimizers import Adam

(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train = x_train.reshape(60000, 784)
x_test = x_test.reshape(10000, 784)

x_train = x_train.astype(np.float32) / 255.
x_test = x_test.astype(np.float32) / 255.

y_train = tf.keras.utils.to_categorical(y_train, 10)
y_test = tf.keras.utils.to_categorical(y_test, 10)

In [ ]:
n_input = 784
n_hidden = 1024
n_output=10

mlp = Sequential()
mlp.add(Dense(units=n_hidden,
              activation='tanh',
              input_shape=(n_input, ),
              kernel_initializer='random_uniform',
              bias_initializer='zeros'))
mlp.add(Dense(units = n_output,
              activation='tanh',
              kernel_initializer='random_uniform',
              bias_initializer='zeros'))


In [ ]:
mlp.compile(loss='mean_squared_error',
            optimizer=Adam(learning_rate=0.001),
            metrics=['accuracy'])
hist = mlp.fit(x_train, y_train, batch_size=128, epochs=30, validation_data=(x_test, y_test), verbose=2)
res = mlp.evaluate(x_test, y_test, verbose=0)
print(f"accuracy = {res[1] * 100}")

Epoch 1/30
469/469 - 6s - loss: 0.0432 - accuracy: 0.8409 - val_loss: 0.0280 - val_accuracy: 0.9144
Epoch 2/30
469/469 - 6s - loss: 0.0226 - accuracy: 0.9272 - val_loss: 0.0188 - val_accuracy: 0.9418
Epoch 3/30
469/469 - 6s - loss: 0.0166 - accuracy: 0.9469 - val_loss: 0.0146 - val_accuracy: 0.9519
Epoch 4/30


KeyboardInterrupt: ignored